# Generated by Django 6.1.1 on 2026-09-26 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificador', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Validación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.delegacion')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='CompromisoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('fecha_limite', models.DateField()),
                ('estado_color', models.CharField(choices=[('BLANCO', 'Reciente'), ('VERDE', 'A tiempo'), ('AMARILLO', 'Próximo a vencer'), ('ROJO', 'Vencido')], default='BLANCO', max_length=10)),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.delegacion')),
                ('funcionario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='evidencias/antes/')),
                ('foto_despues', models.ImageField(blank=True, null=True, upload_to='evidencias/despues/')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidencia', to='seguimiento.actividad')),
            ],
        ),
    ]
